-- 코드를 작성해주세요

SELECT ID, FISH_NAME_INFO.FISH_NAME, A.MAXLEN AS LENGTH
FROM FISH_INFO
JOIN FISH_NAME_INFO ON FISH_INFO.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
JOIN (SELECT FISH_TYPE, MAX(LENGTH) AS MAXLEN
FROM FISH_INFO
GROUP BY FISH_TYPE) AS A ON A.FISH_TYPE=FISH_INFO.FISH_TYPE
WHERE A.MAXLEN=LENGTH